/**
 * Vite Environment Type Definitions
 *
 * This file provides TypeScript type definitions for Vite-specific features.
 * It enables type safety when using Vite's environment variables and client-side APIs.
 *
 * Key features enabled:
 * - import.meta.env for environment variables
 * - import.meta.hot for Hot Module Replacement (HMR)
 * - Static asset imports (images, fonts, etc.)
 * - Vite-specific module resolution
 *
 * This file is automatically generated by Vite and should not be modified manually.
 */

/// <reference types="vite/client" />
