"""add strava_athlete_id column

Revision ID: 5216de56eb03
Revises: ead4347b116f
Create Date: 2026-04-18 02:54:25.980990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5216de56eb03'
down_revision: Union[str, Sequence[str], None] = 'ead4347b116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strava_tokens', sa.Column('strava_athlete_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_strava_tokens_strava_athlete_id'), 'strava_tokens', ['strava_athlete_id'], unique=True)
    op.create_unique_constraint('uq_strava_tokens_athlete_id', 'strava_tokens', ['strava_athlete_id'])
    op.create_foreign_key('fk_strava_tokens_user_id', 'strava_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_strava_tokens_user_id', 'strava_tokens', type_='foreignkey')
    op.drop_constraint('uq_strava_tokens_athlete_id', 'strava_tokens', type_='unique')
    op.drop_index(op.f('ix_strava_tokens_strava_athlete_id'), table_name='strava_tokens')
    op.drop_column('strava_tokens', 'strava_athlete_id')
    # ### end Alembic commands ###
